/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsNewRouteImport } from './routes/groups/new'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as GroupsGroupIdIndexRouteImport } from './routes/groups/$groupId/index'
import { Route as GroupsGroupIdSettingsRouteImport } from './routes/groups/$groupId/settings'
import { Route as GroupsJoinInviteCodeRouteImport } from './routes/groups/join.$inviteCode'
import { Route as GroupsGroupIdPostsPostIdRouteImport } from './routes/groups/$groupId/posts.$postId'
import { Route as GroupsGroupIdPostsNewRouteImport } from './routes/groups/$groupId/posts.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsNewRoute = GroupsNewRouteImport.update({
  id: '/groups/new',
  path: '/groups/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdIndexRoute = GroupsGroupIdIndexRouteImport.update({
  id: '/groups/$groupId/',
  path: '/groups/$groupId/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdSettingsRoute = GroupsGroupIdSettingsRouteImport.update({
  id: '/groups/$groupId/settings',
  path: '/groups/$groupId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsJoinInviteCodeRoute = GroupsJoinInviteCodeRouteImport.update({
  id: '/groups/join/$inviteCode',
  path: '/groups/join/$inviteCode',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdPostsPostIdRoute =
  GroupsGroupIdPostsPostIdRouteImport.update({
    id: '/groups/$groupId/posts/$postId',
    path: '/groups/$groupId/posts/$postId',
    getParentRoute: () => rootRouteImport,
  } as any)
const GroupsGroupIdPostsNewRoute = GroupsGroupIdPostsNewRouteImport.update({
  id: '/groups/$groupId/posts/new',
  path: '/groups/$groupId/posts/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/groups/new': typeof GroupsNewRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/groups/$groupId/settings': typeof GroupsGroupIdSettingsRoute
  '/groups/join/$inviteCode': typeof GroupsJoinInviteCodeRoute
  '/groups/$groupId/': typeof GroupsGroupIdIndexRoute
  '/groups/$groupId/posts/$postId': typeof GroupsGroupIdPostsPostIdRoute
  '/groups/$groupId/posts/new': typeof GroupsGroupIdPostsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/groups/new': typeof GroupsNewRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/groups/$groupId/settings': typeof GroupsGroupIdSettingsRoute
  '/groups/join/$inviteCode': typeof GroupsJoinInviteCodeRoute
  '/groups/$groupId': typeof GroupsGroupIdIndexRoute
  '/groups/$groupId/posts/$postId': typeof GroupsGroupIdPostsPostIdRoute
  '/groups/$groupId/posts/new': typeof GroupsGroupIdPostsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/groups/new': typeof GroupsNewRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/groups/$groupId/settings': typeof GroupsGroupIdSettingsRoute
  '/groups/join/$inviteCode': typeof GroupsJoinInviteCodeRoute
  '/groups/$groupId/': typeof GroupsGroupIdIndexRoute
  '/groups/$groupId/posts/$postId': typeof GroupsGroupIdPostsPostIdRoute
  '/groups/$groupId/posts/new': typeof GroupsGroupIdPostsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/groups/new'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/groups/$groupId/settings'
    | '/groups/join/$inviteCode'
    | '/groups/$groupId/'
    | '/groups/$groupId/posts/$postId'
    | '/groups/$groupId/posts/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/groups/new'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/groups/$groupId/settings'
    | '/groups/join/$inviteCode'
    | '/groups/$groupId'
    | '/groups/$groupId/posts/$postId'
    | '/groups/$groupId/posts/new'
  id:
    | '__root__'
    | '/'
    | '/groups/new'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/groups/$groupId/settings'
    | '/groups/join/$inviteCode'
    | '/groups/$groupId/'
    | '/groups/$groupId/posts/$postId'
    | '/groups/$groupId/posts/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroupsNewRoute: typeof GroupsNewRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  GroupsGroupIdSettingsRoute: typeof GroupsGroupIdSettingsRoute
  GroupsJoinInviteCodeRoute: typeof GroupsJoinInviteCodeRoute
  GroupsGroupIdIndexRoute: typeof GroupsGroupIdIndexRoute
  GroupsGroupIdPostsPostIdRoute: typeof GroupsGroupIdPostsPostIdRoute
  GroupsGroupIdPostsNewRoute: typeof GroupsGroupIdPostsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/new': {
      id: '/groups/new'
      path: '/groups/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof GroupsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/': {
      id: '/groups/$groupId/'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId/'
      preLoaderRoute: typeof GroupsGroupIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/settings': {
      id: '/groups/$groupId/settings'
      path: '/groups/$groupId/settings'
      fullPath: '/groups/$groupId/settings'
      preLoaderRoute: typeof GroupsGroupIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/join/$inviteCode': {
      id: '/groups/join/$inviteCode'
      path: '/groups/join/$inviteCode'
      fullPath: '/groups/join/$inviteCode'
      preLoaderRoute: typeof GroupsJoinInviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/posts/$postId': {
      id: '/groups/$groupId/posts/$postId'
      path: '/groups/$groupId/posts/$postId'
      fullPath: '/groups/$groupId/posts/$postId'
      preLoaderRoute: typeof GroupsGroupIdPostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/posts/new': {
      id: '/groups/$groupId/posts/new'
      path: '/groups/$groupId/posts/new'
      fullPath: '/groups/$groupId/posts/new'
      preLoaderRoute: typeof GroupsGroupIdPostsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroupsNewRoute: GroupsNewRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  GroupsGroupIdSettingsRoute: GroupsGroupIdSettingsRoute,
  GroupsJoinInviteCodeRoute: GroupsJoinInviteCodeRoute,
  GroupsGroupIdIndexRoute: GroupsGroupIdIndexRoute,
  GroupsGroupIdPostsPostIdRoute: GroupsGroupIdPostsPostIdRoute,
  GroupsGroupIdPostsNewRoute: GroupsGroupIdPostsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
